
export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO_BY_ID = 'DELETE_TODO_BY_ID'
// export const EDIT_TODO = 'EDIT_TODO'
export const TOGGLE_TODO_COMPLETE = 'COMPLETE_TODO_COMPLETE'
// export const COMPLETE_ALL_TODOS = 'COMPLETE_ALL_TODOS'
export const CLEAR_COMPLETED_TODOS = 'CLEAR_COMPLETED_TODOS'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'